//
//  DogBreedDetailsManager.swift
//  IDDog
//
//  Created by Vladimir Mironiuk on 03.03.2020.
//  Copyright © 2020 Vladimir Mironiuk. All rights reserved.
//

import Foundation

struct DogBreedDetailsManager {
  
  // MARK: - Properties
  
  private let dogBreedDetails = [
    K.DogBreedKey.chihuahua : DogBreedDetail(breedName: "Chihuahua", wikiURLString: "https://en.wikipedia.org/wiki/Chihuahua_(dog)"),
    K.DogBreedKey.japaneseSpaniel : DogBreedDetail(breedName: "Japanese Chin", wikiURLString: "https://en.wikipedia.org/wiki/Japanese_Chin"),
    K.DogBreedKey.malteseDog : DogBreedDetail(breedName: "Maltese", wikiURLString: "https://en.wikipedia.org/wiki/Maltese_(dog)"),
    K.DogBreedKey.pekinese : DogBreedDetail(breedName: "Pekingese", wikiURLString: "https://en.wikipedia.org/wiki/Pekingese"),
    K.DogBreedKey.shihTzu : DogBreedDetail(breedName: "Shih Tzu", wikiURLString: "https://en.wikipedia.org/wiki/Shih_Tzu"),
    K.DogBreedKey.blenheimSpaniel : DogBreedDetail(breedName: "King Charles Spaniel", wikiURLString: "https://en.wikipedia.org/wiki/King_Charles_Spaniel"),
    K.DogBreedKey.papillon : DogBreedDetail(breedName: "Papillon", wikiURLString: "https://en.wikipedia.org/wiki/Papillon_(dog)"),
    K.DogBreedKey.toyTerrier : DogBreedDetail(breedName: "Toy Terrier", wikiURLString: "https://en.wikipedia.org/wiki/List_of_Toy_Terriers"),
    K.DogBreedKey.rhodesianRidgeback : DogBreedDetail(breedName: "Rhodesian Ridgeback", wikiURLString: "https://en.wikipedia.org/wiki/Rhodesian_Ridgeback"),
    K.DogBreedKey.afghanHound : DogBreedDetail(breedName: "Afghan Hound", wikiURLString: "https://en.wikipedia.org/wiki/Afghan_Hound"),
    K.DogBreedKey.basset : DogBreedDetail(breedName: "Basset Hound", wikiURLString: "https://en.wikipedia.org/wiki/Basset_Hound"),
    K.DogBreedKey.beagle : DogBreedDetail(breedName: "Beagle", wikiURLString: "https://en.wikipedia.org/wiki/Beagle"),
    K.DogBreedKey.bloodhound : DogBreedDetail(breedName: "Bloodhound", wikiURLString: "https://en.wikipedia.org/wiki/Bloodhound"),
    K.DogBreedKey.bluetick : DogBreedDetail(breedName: "Bluetick Coonhound", wikiURLString: "https://en.wikipedia.org/wiki/Bluetick_Coonhound"),
    K.DogBreedKey.blackAndTanCoonhound : DogBreedDetail(breedName: "Black and Tan Coonhound", wikiURLString: "https://en.wikipedia.org/wiki/Black_and_Tan_Coonhound"),
    K.DogBreedKey.walkerHound : DogBreedDetail(breedName: "Treeing Walker Coonhound", wikiURLString: "https://en.wikipedia.org/wiki/Treeing_Walker_Coonhound"),
    K.DogBreedKey.englishFoxhound : DogBreedDetail(breedName: "English Foxhound", wikiURLString: "https://en.wikipedia.org/wiki/English_Foxhound"),
    K.DogBreedKey.redbone : DogBreedDetail(breedName: "Redbone Coonhound", wikiURLString: "https://en.wikipedia.org/wiki/Redbone_Coonhound"),
    K.DogBreedKey.borzoi : DogBreedDetail(breedName: "Borzoi", wikiURLString: "https://en.wikipedia.org/wiki/Borzoi"),
    K.DogBreedKey.irishWolfhound : DogBreedDetail(breedName: "Irish Wolfhound", wikiURLString: "https://en.wikipedia.org/wiki/Irish_wolfhound"),
    K.DogBreedKey.italianGreyhound : DogBreedDetail(breedName: "Italian Greyhound", wikiURLString: "https://en.wikipedia.org/wiki/Italian_Greyhound"),
    K.DogBreedKey.whippet : DogBreedDetail(breedName: "Whippet", wikiURLString: "https://en.wikipedia.org/wiki/Whippet"),
    K.DogBreedKey.ibizanHound : DogBreedDetail(breedName: "Ibizan Hound", wikiURLString: "https://en.wikipedia.org/wiki/Ibizan_Hound"),
    K.DogBreedKey.norwegianElkhound : DogBreedDetail(breedName: "Norwegian Elkhound", wikiURLString: "https://en.wikipedia.org/wiki/Norwegian_Elkhound"),
    K.DogBreedKey.otterhound : DogBreedDetail(breedName: "Otterhound", wikiURLString: "https://en.wikipedia.org/wiki/Otterhound"),
    K.DogBreedKey.saluki : DogBreedDetail(breedName: "Saluki", wikiURLString: "https://en.wikipedia.org/wiki/Saluki"),
    K.DogBreedKey.scottishDeerhound : DogBreedDetail(breedName: "Scottish Deerhound", wikiURLString: "https://en.wikipedia.org/wiki/Scottish_Deerhound"),
    K.DogBreedKey.weimaraner : DogBreedDetail(breedName: "Weimaraner", wikiURLString: "https://en.wikipedia.org/wiki/Weimaraner"),
    K.DogBreedKey.staffordshireBullterrier : DogBreedDetail(breedName: "Staffordshire Bull Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Staffordshire_Bull_Terrier"),
    K.DogBreedKey.americanStaffordshireTerrier : DogBreedDetail(breedName: "American Staffordshire Terrier", wikiURLString: "https://en.wikipedia.org/wiki/American_Staffordshire_Terrier"),
    K.DogBreedKey.bedlingtonTerrier : DogBreedDetail(breedName: "Bedlington Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Bedlington_Terrier"),
    K.DogBreedKey.borderTerrier : DogBreedDetail(breedName: "Border Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Border_Terrier"),
    K.DogBreedKey.kerryBlueTerrier : DogBreedDetail(breedName: "Kerry Blue Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Kerry_Blue_Terrier"),
    K.DogBreedKey.irishTerrier : DogBreedDetail(breedName: "Irish Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Irish_Terrier"),
    K.DogBreedKey.norfolkTerrier : DogBreedDetail(breedName: "Norfolk Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Norfolk_Terrier"),
    K.DogBreedKey.norwichTerrier : DogBreedDetail(breedName: "Norwich Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Norwich_Terrier"),
    K.DogBreedKey.yorkshireTerrier : DogBreedDetail(breedName: "Yorkshire Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Yorkshire_Terrier"),
    K.DogBreedKey.wireHairedFoxTerrier : DogBreedDetail(breedName: "Wire Fox Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Wire_Fox_Terrier"),
    K.DogBreedKey.lakelandTerrier : DogBreedDetail(breedName: "Lakeland Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Lakeland_Terrier"),
    K.DogBreedKey.sealyhamTerrier : DogBreedDetail(breedName: "Sealyham Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Sealyham_Terrier"),
    K.DogBreedKey.airedale : DogBreedDetail(breedName: "Airedale Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Airedale_Terrier"),
    K.DogBreedKey.cairn : DogBreedDetail(breedName: "Cairn Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Cairn_Terrier"),
    K.DogBreedKey.australianTerrier : DogBreedDetail(breedName: "Australian Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Australian_Terrier"),
    K.DogBreedKey.dandieDinmont : DogBreedDetail(breedName: "Dandie Dinmont Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Dandie_Dinmont_Terrier"),
    K.DogBreedKey.bostonBull : DogBreedDetail(breedName: "Boston Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Boston_Terrier"),
    K.DogBreedKey.miniatureSchnauzer : DogBreedDetail(breedName: "Miniature Schnauzer", wikiURLString: "https://en.wikipedia.org/wiki/Miniature_Schnauzer"),
    K.DogBreedKey.giantSchnauzer : DogBreedDetail(breedName: "Giant Schnauzer", wikiURLString: "https://en.wikipedia.org/wiki/Giant_Schnauzer"),
    K.DogBreedKey.standardSchnauzer : DogBreedDetail(breedName: "Standard Schnauzer", wikiURLString: "https://en.wikipedia.org/wiki/Standard_Schnauzer"),
    K.DogBreedKey.scotchTerrier : DogBreedDetail(breedName: "Scottish Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Scottish_Terrier"),
    K.DogBreedKey.tibetanTerrier : DogBreedDetail(breedName: "Tibetan Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Tibetan_Terrier"),
    K.DogBreedKey.silkyTerrier : DogBreedDetail(breedName: "Australian Silky Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Australian_Silky_Terrier"),
    K.DogBreedKey.softCoatedWheatenTerrier : DogBreedDetail(breedName: "Soft-coated Wheaten Terrier", wikiURLString: "https://en.wikipedia.org/wiki/Soft-coated_Wheaten_Terrier"),
    K.DogBreedKey.westHighlandWhiteTerrier : DogBreedDetail(breedName: "West Highland White Terrier", wikiURLString: "https://en.wikipedia.org/wiki/West_Highland_White_Terrier"),
    K.DogBreedKey.lhasa : DogBreedDetail(breedName: "Lhasa Apso", wikiURLString: "https://en.wikipedia.org/wiki/Lhasa_Apso"),
    K.DogBreedKey.flatCoatedRetriever : DogBreedDetail(breedName: "Flat-coated Retriever", wikiURLString: "https://en.wikipedia.org/wiki/Flat-coated_Retriever"),
    K.DogBreedKey.curlyCoatedRetriever : DogBreedDetail(breedName: "Curly-coated Retriever", wikiURLString: "https://en.wikipedia.org/wiki/Curly-coated_Retriever"),
    K.DogBreedKey.goldenRetriever : DogBreedDetail(breedName: "Golden Retriever", wikiURLString: "https://en.wikipedia.org/wiki/Golden_Retriever"),
    K.DogBreedKey.labradorRetriever : DogBreedDetail(breedName: "Labrador Retriever", wikiURLString: "https://en.wikipedia.org/wiki/Labrador_Retriever"),
    K.DogBreedKey.chesapeakeBayRetriever : DogBreedDetail(breedName: "Chesapeake Bay Retriever", wikiURLString: "https://en.wikipedia.org/wiki/Chesapeake_Bay_Retriever"),
    K.DogBreedKey.germanShortHairedPointer : DogBreedDetail(breedName: "German Shorthaired Pointer", wikiURLString: "https://en.wikipedia.org/wiki/German_Shorthaired_Pointer"),
    K.DogBreedKey.vizsla : DogBreedDetail(breedName: "Vizsla", wikiURLString: "https://en.wikipedia.org/wiki/Vizsla"),
    K.DogBreedKey.englishSetter : DogBreedDetail(breedName: "English Setter", wikiURLString: "https://en.wikipedia.org/wiki/English_Setter"),
    K.DogBreedKey.irishSetter : DogBreedDetail(breedName: "Irish Setter", wikiURLString: "https://en.wikipedia.org/wiki/Irish_Setter"),
    K.DogBreedKey.gordonSetter : DogBreedDetail(breedName: "Gordon Setter", wikiURLString: "https://en.wikipedia.org/wiki/Gordon_Setter"),
    K.DogBreedKey.brittanySpaniel : DogBreedDetail(breedName: "Brittany", wikiURLString: "https://en.wikipedia.org/wiki/Brittany_(dog)"),
    K.DogBreedKey.clumber : DogBreedDetail(breedName: "Clumber Spaniel", wikiURLString: "https://en.wikipedia.org/wiki/Clumber_Spaniel"),
    K.DogBreedKey.englishSpringer : DogBreedDetail(breedName: "English Springer Spaniel", wikiURLString: "https://en.wikipedia.org/wiki/English_Springer_Spaniel"),
    K.DogBreedKey.welshSpringerSpaniel : DogBreedDetail(breedName: "Welsh Springer Spaniel", wikiURLString: "https://en.wikipedia.org/wiki/Welsh_Springer_Spaniel"),
    K.DogBreedKey.cockerSpaniel : DogBreedDetail(breedName: "Cocker Spaniel", wikiURLString: "https://en.wikipedia.org/wiki/Cocker_Spaniel"),
    K.DogBreedKey.sussexSpaniel : DogBreedDetail(breedName: "Sussex Spaniel", wikiURLString: "https://en.wikipedia.org/wiki/Sussex_Spaniel"),
    K.DogBreedKey.irishWaterSpaniel : DogBreedDetail(breedName: "Irish Water Spaniel", wikiURLString: "https://en.wikipedia.org/wiki/Irish_Water_Spaniel"),
    K.DogBreedKey.kuvasz : DogBreedDetail(breedName: "Kuvasz", wikiURLString: "https://en.wikipedia.org/wiki/Kuvasz"),
    K.DogBreedKey.schipperke : DogBreedDetail(breedName: "Schipperke", wikiURLString: "https://en.wikipedia.org/wiki/Schipperke"),
    K.DogBreedKey.groenendael : DogBreedDetail(breedName: "Groenendael", wikiURLString: "https://en.wikipedia.org/wiki/Groenendael_dog"),
    K.DogBreedKey.malinois : DogBreedDetail(breedName: "Malinois", wikiURLString: "https://en.wikipedia.org/wiki/Malinois_dog"),
    K.DogBreedKey.briard : DogBreedDetail(breedName: "Briard", wikiURLString: "https://en.wikipedia.org/wiki/Briard"),
    K.DogBreedKey.kelpie : DogBreedDetail(breedName: "Australian Kelpie", wikiURLString: "https://en.wikipedia.org/wiki/Australian_Kelpie"),
    K.DogBreedKey.komondor : DogBreedDetail(breedName: "Komondor", wikiURLString: "https://en.wikipedia.org/wiki/Komondor"),
    K.DogBreedKey.oldEnglishSheepdog : DogBreedDetail(breedName: "Old English Sheepdog", wikiURLString: "https://en.wikipedia.org/wiki/Old_English_Sheepdog"),
    K.DogBreedKey.shetlandSheepdog : DogBreedDetail(breedName: "Shetland Sheepdog", wikiURLString: "https://en.wikipedia.org/wiki/Shetland_Sheepdog"),
    K.DogBreedKey.collie : DogBreedDetail(breedName: "Rough Collie", wikiURLString: "https://en.wikipedia.org/wiki/Rough_Collie"),
    K.DogBreedKey.borderCollie : DogBreedDetail(breedName: "Border Collie", wikiURLString: "https://en.wikipedia.org/wiki/Border_Collie"),
    K.DogBreedKey.bouvierDesFlandres : DogBreedDetail(breedName: "Bouvier des Flandres", wikiURLString: "https://en.wikipedia.org/wiki/Bouvier_des_Flandres"),
    K.DogBreedKey.rottweiler : DogBreedDetail(breedName: "Rottweiler", wikiURLString: "https://en.wikipedia.org/wiki/Rottweiler"),
    K.DogBreedKey.germanShepherd : DogBreedDetail(breedName: "German Shepherd", wikiURLString: "https://en.wikipedia.org/wiki/German_Shepherd"),
    K.DogBreedKey.doberman : DogBreedDetail(breedName: "Dobermann", wikiURLString: "https://en.wikipedia.org/wiki/Dobermann"),
    K.DogBreedKey.miniaturePinscher : DogBreedDetail(breedName: "Miniature Pinscher", wikiURLString: "https://en.wikipedia.org/wiki/Miniature_Pinscher"),
    K.DogBreedKey.greaterSwissMountainDog : DogBreedDetail(breedName: "Greater Swiss Mountain Dog", wikiURLString: "https://en.wikipedia.org/wiki/Greater_Swiss_Mountain_Dog"),
    K.DogBreedKey.berneseMountainDog : DogBreedDetail(breedName: "Bernese Mountain Dog", wikiURLString: "https://en.wikipedia.org/wiki/Bernese_Mountain_Dog"),
    K.DogBreedKey.appenzeller : DogBreedDetail(breedName: "Appenzeller Sennenhund", wikiURLString: "https://en.wikipedia.org/wiki/Appenzeller_Sennenhund"),
    K.DogBreedKey.entleBucher : DogBreedDetail(breedName: "Entlebucher Mountain Dog", wikiURLString: "https://en.wikipedia.org/wiki/Entlebucher_Mountain_Dog"),
    K.DogBreedKey.boxer : DogBreedDetail(breedName: "Boxer", wikiURLString: "https://en.wikipedia.org/wiki/Boxer_(dog)"),
    K.DogBreedKey.bullMastiff : DogBreedDetail(breedName: "Bullmastiff", wikiURLString: "https://en.wikipedia.org/wiki/Bullmastiff"),
    K.DogBreedKey.tibetanMastiff : DogBreedDetail(breedName: "Tibetan Mastiff", wikiURLString: "https://en.wikipedia.org/wiki/Tibetan_Mastiff"),
    K.DogBreedKey.frenchBulldog : DogBreedDetail(breedName: "French Bulldog", wikiURLString: "https://en.wikipedia.org/wiki/French_Bulldog"),
    K.DogBreedKey.greatDane : DogBreedDetail(breedName: "Great Dane", wikiURLString: "https://en.wikipedia.org/wiki/Great_Dane"),
    K.DogBreedKey.saintBernard : DogBreedDetail(breedName: "St. Bernard", wikiURLString: "https://en.wikipedia.org/wiki/St._Bernard_(dog)"),
    K.DogBreedKey.eskimoDog : DogBreedDetail(breedName: "Eskimo dog", wikiURLString: "https://en.wikipedia.org/wiki/Eskimo_dog"),
    K.DogBreedKey.malamute : DogBreedDetail(breedName: "Alaskan Malamute", wikiURLString: "https://en.wikipedia.org/wiki/Alaskan_Malamute"),
    K.DogBreedKey.siberianHusky : DogBreedDetail(breedName: "Siberian Husky", wikiURLString: "https://en.wikipedia.org/wiki/Siberian_Husky"),
    K.DogBreedKey.affenpinscher : DogBreedDetail(breedName: "Affenpinscher", wikiURLString: "https://en.wikipedia.org/wiki/Affenpinscher"),
    K.DogBreedKey.basenji : DogBreedDetail(breedName: "Basenji", wikiURLString: "https://en.wikipedia.org/wiki/Basenji"),
    K.DogBreedKey.pug : DogBreedDetail(breedName: "Pug", wikiURLString: "https://en.wikipedia.org/wiki/Pug"),
    K.DogBreedKey.leonberg : DogBreedDetail(breedName: "Leonberger", wikiURLString: "https://en.wikipedia.org/wiki/Leonberger"),
    K.DogBreedKey.newfoundland : DogBreedDetail(breedName: "Newfoundland", wikiURLString: "https://en.wikipedia.org/wiki/Newfoundland_(dog)"),
    K.DogBreedKey.greatPyrenees : DogBreedDetail(breedName: "Great Pyrenees", wikiURLString: "https://en.wikipedia.org/wiki/Great_Pyrenees"),
    K.DogBreedKey.samoyed : DogBreedDetail(breedName: "Samoyed", wikiURLString: "https://en.wikipedia.org/wiki/Samoyed_(dog)"),
    K.DogBreedKey.pomeranian : DogBreedDetail(breedName: "Pomeranian", wikiURLString: "https://en.wikipedia.org/wiki/Pomeranian_(dog)"),
    K.DogBreedKey.keeshond : DogBreedDetail(breedName: "Keeshond", wikiURLString: "https://en.wikipedia.org/wiki/Keeshond"),
    K.DogBreedKey.brabanconGriffon : DogBreedDetail(breedName: "Griffon Bruxellois", wikiURLString: "https://en.wikipedia.org/wiki/Griffon_Bruxellois"),
    K.DogBreedKey.pembroke : DogBreedDetail(breedName: "Pembroke Welsh Corgi", wikiURLString: "https://en.wikipedia.org/wiki/Pembroke_Welsh_Corgi"),
    K.DogBreedKey.cardigan : DogBreedDetail(breedName: "Cardigan Welsh Corgi", wikiURLString: "https://en.wikipedia.org/wiki/Cardigan_Welsh_Corgi"),
    K.DogBreedKey.toyPoodle : DogBreedDetail(breedName: "Toy Poodle", wikiURLString: "https://en.wikipedia.org/wiki/Poodle#Size_variants"),
    K.DogBreedKey.miniaturePoodle : DogBreedDetail(breedName: "Miniature Poodle", wikiURLString: "https://en.wikipedia.org/wiki/Poodle#Size_variants"),
    K.DogBreedKey.standardPoodle : DogBreedDetail(breedName: "Poodle", wikiURLString: "https://en.wikipedia.org/wiki/Poodle"),
    K.DogBreedKey.mexicanHairless : DogBreedDetail(breedName: "Xoloitzcuintle", wikiURLString: "https://en.wikipedia.org/wiki/Xoloitzcuintle"),
    K.DogBreedKey.dingo : DogBreedDetail(breedName: "Dingo", wikiURLString: "https://en.wikipedia.org/wiki/Dingo"),
    K.DogBreedKey.dhole : DogBreedDetail(breedName: "Dhole", wikiURLString: "https://en.wikipedia.org/wiki/Dhole"),
    K.DogBreedKey.africanHuntingDog : DogBreedDetail(breedName: "African wild dog", wikiURLString: "https://en.wikipedia.org/wiki/African_wild_dog")
  ]

  // MARK: - Public
  
  func dogBreedDetail(forKey key: String) -> DogBreedDetail? {
    guard let key = K.DogBreedKey(rawValue: key) else {
      return nil
    }
    return self.dogBreedDetails[key]
  }
}
